//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInvities.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalProperty
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public short AddressID { get; set; }
        public short YearBuilt { get; set; }
        public decimal MonthlyHOAFee { get; set; }
        public short Building { get; set; }
    
        public virtual PostalAddress PostalAddress { get; set; }
    }
}
